# Generated by Django 2.0.2 on 2018-12-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='imageTitle',
            field=models.CharField(default='Image', max_length=120),
        ),
    ]
