# Generated by Django 2.0.2 on 2018-12-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_auto_20181212_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='imageTitle',
            field=models.CharField(max_length=120),
        ),
    ]
