# Generated by Django 2.0.2 on 2018-12-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_auto_20181212_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
