# Generated by Django 2.0.2 on 2018-12-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0005_auto_20181212_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '1. Slider',
            },
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': '3. Certificates'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': '2. Gallery'},
        ),
    ]
