# Generated by Django 2.0.2 on 2018-12-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0006_auto_20181214_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='imagesSlider',
        ),
    ]
