# Generated by Django 2.0.2 on 2018-12-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0008_auto_20181219_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoHeader', models.CharField(max_length=100)),
                ('videoEmbedLink', models.URLField(help_text="Video > Share > Embed > src = 'videoEmbedLink' ")),
            ],
        ),
    ]
