# Generated by Django 2.0.2 on 2018-12-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '1. Contact'},
        ),
    ]
