# Generated by Django 2.0.2 on 2018-12-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(help_text='Image height = Text height', max_length=220)),
                ('image', models.ImageField(help_text='Image height = Text height', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '2. Services',
            },
        ),
    ]
