# Generated by Django 2.0.2 on 2018-12-13 15:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_auto_20181213_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('image1', models.ImageField(blank=True, help_text='Optional', upload_to='images/')),
                ('image2', models.ImageField(blank=True, help_text='Optional', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '3. Product',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': '2. serviceCategory'},
        ),
        migrations.AddField(
            model_name='product',
            name='serviceCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='Services.Service'),
        ),
    ]
