# Generated by Django 2.0.2 on 2018-12-14 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_auto_20181214_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serviceCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product', to='Services.Service'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
