# Generated by Django 2.0.2 on 2018-12-14 04:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_auto_20181214_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='detailImage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
