# Generated by Django 2.0.2 on 2018-12-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_auto_20181214_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sliderImage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
