# Generated by Django 2.0.2 on 2018-12-17 07:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_auto_20181214_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='detailImage',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='productImage1',
            field=models.ImageField(blank=True, default='', help_text='Optional', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='productImage2',
            field=models.ImageField(blank=True, default='', help_text='Optional', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='serviceCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Products', to='Services.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
