# Generated by Django 2.0.2 on 2018-12-17 07:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0011_auto_20181217_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='productDescription',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Image height = Text height', max_length=220),
        ),
    ]
