# Generated by Django 2.0.2 on 2018-12-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0013_auto_20181217_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(help_text='amount of categories has to be less than or equal to amount of products', max_length=50),
        ),
    ]
