# Generated by Django 2.0.2 on 2019-01-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0016_auto_20190104_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='detailImage',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
