# Generated by Django 2.0.2 on 2018-12-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_auto_20181214_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonialSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '4. testimonialSlider',
            },
        ),
    ]
