# Generated by Django 2.0.2 on 2018-12-14 10:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_testimonialslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=120)),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': '5. Testimonials',
            },
        ),
    ]
