# Generated by Django 2.0.2 on 2018-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField()),
                ('blogCategory', models.CharField(max_length=60)),
                ('header', models.CharField(default='', max_length=120)),
                ('blogDescription', models.TextField()),
                ('editorImage', models.ImageField(upload_to='images/')),
                ('editor', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': '2. Blog',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '1. Slider',
            },
        ),
    ]
