# Generated by Django 2.0.2 on 2018-12-11 08:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
