# Generated by Django 2.0.2 on 2018-12-18 03:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageTitle', models.CharField(default=' ', max_length=40)),
                ('image', models.ImageField(help_text='max height = 80px', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '5. Clients',
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('detailImage', models.ImageField(default='', upload_to='images/')),
                ('detailText', ckeditor.fields.RichTextField(default='', help_text='Sub headers should be heading 3')),
            ],
            options={
                'verbose_name_plural': '4. Founders',
            },
        ),
        migrations.CreateModel(
            name='internationalPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageTitle', models.CharField(default=' ', max_length=40)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '7. internationalPartners',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '1. Slider',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('testimonial', models.TextField(help_text='No Quotes Needed')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name_plural': '6. Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=120)),
                ('subTitle', models.CharField(blank=True, max_length=400)),
                ('image', models.ImageField(upload_to='images/')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': '2. Welcome',
            },
        ),
    ]
