# Generated by Django 2.0.2 on 2018-12-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20181211_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name_plural': 'Welcome'},
        ),
        migrations.AddField(
            model_name='welcome',
            name='subTitle',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='welcome',
            name='title',
            field=models.CharField(default='Title goes here', max_length=120),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
