# Generated by Django 2.0.2 on 2019-01-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_bestservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
