# Generated by Django 2.0.2 on 2018-12-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20181211_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Title goes here', max_length=120)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
