# Generated by Django 2.0.2 on 2018-12-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20181211_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bestServices',
            new_name='bestService',
        ),
    ]
