# Generated by Django 2.0.2 on 2018-12-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20181211_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestservice',
            name='description',
            field=models.CharField(max_length=220),
        ),
    ]
