# Generated by Django 2.0.2 on 2018-12-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20181211_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestservice',
            name='description',
            field=models.CharField(help_text='Image height = Text height', max_length=220),
        ),
    ]
