# Generated by Django 2.0.2 on 2018-12-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20181211_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestservice',
            name='image',
            field=models.ImageField(help_text='Image height = Text height', upload_to='images/'),
        ),
    ]
