# Generated by Django 2.0.2 on 2018-12-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestservice',
            name='description',
            field=models.TextField(help_text='Image height = Text height', max_length=220),
        ),
        migrations.AlterField(
            model_name='founder',
            name='position',
            field=models.TextField(max_length=250),
        ),
    ]
