# Generated by Django 2.0.2 on 2018-12-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20181212_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
