# Generated by Django 2.0.2 on 2018-12-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='imageTitle',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(help_text='max height = 80px', upload_to='images/'),
        ),
    ]
