# Generated by Django 2.0.2 on 2018-12-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20181212_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('testimonial', models.TextField()),
                ('name', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
