# Generated by Django 2.0.2 on 2018-12-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(help_text='No Quotes Needed'),
        ),
    ]
