# Generated by Django 2.0.2 on 2018-12-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20181212_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestservice',
            options={'verbose_name_plural': '3. bestServices'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': '5. Clients'},
        ),
        migrations.AlterModelOptions(
            name='founder',
            options={'verbose_name_plural': '4. Founders'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '1. Sliders'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': '6. Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name_plural': '2. Welcome'},
        ),
    ]
