# Generated by Django 2.0.2 on 2018-12-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_auto_20181212_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='internationalPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageTitle', models.CharField(default=' ', max_length=40)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '7. internationalPartners',
            },
        ),
    ]
