# Generated by Django 2.0.2 on 2018-12-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_auto_20181212_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='updated_at',
        ),
    ]
