# Generated by Django 2.0.2 on 2018-12-13 07:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_founder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='detailImage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='founder',
            name='detailText',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
