# Generated by Django 2.0.2 on 2018-12-13 08:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_auto_20181213_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='detailText',
            field=ckeditor.fields.RichTextField(default='', help_text='Sub headers should be heading 3'),
        ),
    ]
