# Generated by Django 2.0.2 on 2018-12-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_auto_20181213_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '1. Slider'},
        ),
    ]
