# Generated by Django 2.0.2 on 2018-12-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'verbose_name_plural': '1. Segments'},
        ),
    ]
