# Generated by Django 2.0.2 on 2018-12-12 07:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_auto_20181212_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='All sub headers should be header 3'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='title',
            field=models.CharField(help_text='All sub headers should be header 3', max_length=120),
        ),
    ]
