# Generated by Django 2.0.2 on 2019-01-02 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0005_auto_20181214_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['created'], 'verbose_name_plural': '2. Segments'},
        ),
        migrations.RemoveField(
            model_name='segment',
            name='updated',
        ),
    ]
