# Generated by Django 2.0.2 on 2018-12-13 04:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkImage', models.ImageField(help_text='Can be taken from https://www.flaticon.com/', upload_to='images/')),
                ('link', models.CharField(max_length=200)),
                ('address', ckeditor.fields.RichTextField()),
                ('workingHoursHeader', models.CharField(help_text='Office,Email,Mobie,etc', max_length=40)),
                ('workingHoursDetail', models.CharField(help_text='+62 82111997750, info@businessgrowthcorp.com, etc', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='workingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
