# Generated by Django 2.0.2 on 2018-12-13 04:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Footer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Office,Email,Mobie,etc', max_length=40)),
                ('detail', models.CharField(help_text='+62 82111997750, info@businessgrowthcorp.com, etc', max_length=150)),
            ],
            options={
                'verbose_name_plural': '3. Details',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkTitle', models.CharField(help_text='Facebook,Linkedin, etc', max_length=50)),
                ('linkImage', models.ImageField(help_text='Can be taken from https://www.flaticon.com/', upload_to='images/')),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '1. Links',
            },
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.DeleteModel(
            name='workingHours',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': '2. Address'},
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
