# Generated by Django 2.0.2 on 2018-12-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Footer', '0002_auto_20181213_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='whyChooseUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconImage', models.ImageField(help_text='Can be taken from https://www.flaticon.com/', upload_to='images/')),
                ('subHeader', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
